config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#list_posts'

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    devise_for :users

    resources :posts do
      member do
        put 'like', to: 'posts#upvote'
        put 'unlike', to: 'posts#downvote'
      end
    end

    get '/search', to: 'posts#search'
    get '/list_posts', to: 'posts#list_posts'
    get '/list_videos', to: 'posts#list_videos'
    get 'tags/:tag', to: 'posts#index', as: :tag

    resources :comments, only: %i[ create update destroy ] do
      member do
        put 'like', to: 'comments#upvote'
        put 'unlike', to: 'comments#downvote'
      end
    end

    resources :friends, only: %i[ create update destroy ]

    resources :users, only: %i[ show ]
    get '/profile_edit', to: 'users#edit'
    patch '/profile', to: 'users#updade'

end

app/models/comment.rb
class Comment < ApplicationRecord

  acts_as_votable

  belongs_to :post
  belongs_to :user

  enum status: [ :pending, :published, :blocked ]

  validates :commenter, presence: true, length: { minimum: 2, maximum: 240 }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :set_comment, only: %i[ upvote downvote update ]

def create
  @comment = current_user.comments.new(comment_params)
  if @comment.save
    redirect_to @comment.post, notice: 'Comment created with successfully!!!'
  else
    flash.now[:alert] = @comment.errors.full_messages.to_sentence
    redirect_to @comment.post
  end
end

def upvote
  @comment.upvote_from current_user
  redirect_to @comment.post
end

def downvote
  @comment.downvote_from current_user
  redirect_to @comment.post
end

def update
  if @comment.update(comment_params)
    render json: { successull: true}, notice: 'Comments update successfully!!!'
  else
    render json: { successull: false}
    flash.now[:alert] = 'ERROR'
  end
end

def destroy
end

private

def set_comment
  @comment = Comment.find(params[:id])
end

def comment_params
  params.require(:comment).permit(:commenter, :post_id, :status)
end

end

app/views/comments/_comments.html.haml
.comment_list
  - commenter.published.each do |comment|
    .forlikes
      .user_detail.mr-5
        .user_image
          = get_avatar(comment.user)
        .user_description
          %div #{ comment.user.name }
          %span
            %small.is-size-7.has-text-grey
              #{ time_ago_in_words comment.created_at }
      .comments_likes
        .show_votable
          .icones
            .tags.has-addons
              = link_to like_comment_path(comment), method: :put, class: 'tag like' do
                = comment.get_upvotes.size
                %span.ml-2
                  %i.fas.fa-thumbs-up
              = link_to unlike_comment_path(comment), method: :put, class: 'tag like' do
                = comment.get_downvotes.size
                %span.ml-2
                  %i.fas.fa-thumbs-down

    .detail_comments
      %p #{ comment.commenter }

app/views/comments/_form.html.haml
.card_comments
  %h3
    %i.fas.fa-comments
    #{ t 'comment' }(s)
  .icones.mt-4
    .tags.has-addons
      %span.tag
        %b.mr-2 #{ origem.total_comments }
        #{ t 'comment' }(s) &nbsp;
        %span
          %i.fas.fa-comment-alt

  - if user_signed_in?
    .comment_form.mt-5
      = form_with(model: @comment, local: true) do |form|
        = form.hidden_field :post_id, value: origem.id
        .field
          .control
            = form.text_area :commenter, class: 'textarea', rows: 2
        .field.has-text-right
          = form.submit "#{ t 'add' }", class: 'button is-info is-small'

  - else
    -# TODO: Recado para quem não é inscrito ...