config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#list_posts'

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    devise_for :users

    resources :posts do
      member do
        put 'like', to: 'posts#upvote'
        put 'unlike', to: 'posts#downvote'
      end
    end

    get '/search', to: 'posts#search'
    get '/list_posts', to: 'posts#list_posts'
    get '/list_videos', to: 'posts#list_videos'
    get 'tags/:tag', to: 'posts#index', as: :tag

    resources :comments, only: %i[ create update destroy ] do
      member do
        put 'like', to: 'comments#upvote'
        put 'unlike', to: 'comments#downvote'
      end
    end

    resources :friends, only: %i[ create update destroy ]

    resources :users, only: %i[ show ]
    get '/profile_edit', to: 'users#edit'
    patch '/profile', to: 'users#updade'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_voter

  has_many :posts, dependent: :destroy
  has_many :comments
  has_one_attached :avatar
  has_many :friends

  enum kind: [:user, :admin, :manager]
  enum status: [:active, :inactive]
  enum language: ['pt-BR','es','en']

  validates :name, presence: true
  validates :username, uniqueness: true

  before_save do
    self.username = username.downcase.split(' ').join()
  end

  def total_comments
    self.posts.joins(:comments).where(comments: {status: :pending}).count
  end

  def request_friends?(friend)
    self.friends.where(friend: friend).exists?
  end

  def status_friends(friend)
    if request_friends?(friend)
      self.friends.where(friend: friend).pluck(:status).join()
    else
      false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
  @posts = current_user.posts.comments_post_not_published
  @videos = current_user.posts.comments_video_not_published
  # @posts = current_user.posts.list_comments_posts
  # @videos = current_user.posts.list_comments_videos
end

def edit
end

def updade
  if current_user.update(user_params)
    redirect_to user_path(current_user.id), notice: 'User updated successfull'
  else
    flash.now[:alert] = current_user.errors.full_messages.to_sentence
  end
end

private

def user_params
  params.require(:user).permit(:name, :avatar, :language)
end

end

app/views/users/_avatar.html.haml
.user_detail
  .user_image
    = get_avatar(profile)
  .user_description
    %div
      #{ profile.name }
    %span
      = link_to '#' do
        @#{ profile.username }

app/views/users/_perfil_follow.html.haml
.aside_container.mb-3.has-background-dark
  -# .titles
    %i.fas.fa-pencil-alt
    #{ t 'author' }
  .user_detail.p-3
    .user_image
      = get_avatar(profile)
    .user_description.has-text-white
      %div
        #{ profile.name }
      %span
        @#{ profile.username }

  .btn_action.has-text-centered.mt-1
    - if user_signed_in?
      - if current_user != profile
        - if are_friends(current_user.id, profile) > 0
          = link_to '#', class: 'btn-amigos button is-primary is-small is-fullwidth' do
            %i.fas.fa-check-circle.mr-3
            #{t 'friends'}
        - elsif current_user.status_friends(profile) == false
          .action.has-text-white.is-size-5
            = link_to '#', class: 'btn-adicionar button is-info is-small', data:{social_id: profile.id } do
              %i.fas.fa-user-plus.mr-3
              #{t 'add'}
        - else
          = link_to '#', class: 'btn-aguardando button is-light is-small is-static' do
            #{t 'waiting'} ...

app/views/users/_social_follow.html.haml
#user-follow.modals
  %h3.has-text-centered.mb-2 #{ t 'request_friend'}
  - if user_signed_in?
    %table.table.is-striped.is-fullwidth
      %thead
        %th #{ t 'name'}
        %th #{ t 'username'}
        %th{colspan: 3, style: 'width: 10px'}
      %tbody
      - pending_list(current_user.id).each do |friend|
        %tr{class: "tr_social-#{friend.id}"}
          %td #{ friend.name }
          %td #{ friend.username }
          %td
            = link_to :list_posts, class: 'btn-accept', data:{modal_id: "#{set_follow(current_user.id, friend.id)}"} do
              %i.far.fa-thumbs-up
          %td
            = link_to '#', class: 'btn-bloqued' do
              %i.fas.fa-user-lock
          %td
            = link_to '#', class: 'btn-trash' do
              %i.fas.fa-trash-alt

app/views/users/edit.html.haml
%main
  -# = render 'shared/banner'
  .container.mt-4
    .wrapper_content{style: 'min-height: 600px'}
      .show_edit_user
        .base_edit_user
          - if current_user.avatar.attached?
            .figure_edit
              = image_tag current_user.avatar, class: 'photo_user'
          = form_with model: current_user, url: profile_path, local: true, class: 'edit-profile' do |form|
            %h1.has-text-centered #{ t 'add_avatar' }
            .field.mt-4
              = form.label "#{t 'language'}", class: 'label'
              .control
                = form.select :language, [['Brazil','pt-BR'],['USA','en'],['Spain','es']]
            .field
              = form.label :avatar, class: 'label'
              .control
                = form.file_field :avatar

            .actions.has-text-centered
              = form.submit class: 'button is-info'

      -# .grid_aside
        = render 'users/perfil_follow', profile: current_user

app/views/users/show.html.haml
- if user_signed_in?
  %main.mt-4
    .container
      .wrapper_content
        .wrapper_grids
          .show_content{style: 'min-height: 600px'}
            .perfil_show
              .content_perfil
                .panel_tabs
                  .tabs.is-boxed
                    %ul
                      %li.is-active
                        %a
                          %i.fas.fa-comment.mr-2
                          #{t 'article_comments'}

                      %li
                        %a
                          %i.far.fa-comment.mr-2
                          #{t 'videos_comments'}
                      %li
                        %a
                          %i.fas.fa-user.mr-2
                          #{t 'friendship_request'}
                      %li
                        %a
                          %i.fas.fa-user-friends.mr-2
                          #{t 'friends_list'}

                .tab_content
                  .tab_wrapper{style: 'display: block'}
                    %table.table.is-striped.is-fullwidth
                      %thead
                        %tr
                          %th ID
                          %th #{t 'post'}
                          %th #{t 'comment'}(s)
                      %tbody
                        - @posts.each do |post|
                          %tr
                            %td #{ post.id }
                            %td= link_to post.title, post
                            %td
                              %table.table.is-striped.is-fullwidth
                                - post.comments.each do |post_comment|
                                  %tr{class: "cmtPost-#{post_comment.id}"}
                                    %td{width: '80%'} #{ post_comment.commenter }
                                    %td #{ post_comment.status }
                                    %td.action{data:{post:{comment: "#{update_comment(post_comment.id, 'published')}"}}}
                                      .btn_comment_published
                                        %i.fas.fa-lock
                                    %td.action{data:{post:{comment: "#{update_comment(post_comment.id, 'blocked')}"}}}
                                      .btn_comment_published
                                        %i.fas.fa-trash
                  .tab_wrapper
                    %table.table.is-striped.is-fullwidth
                      %thead
                        %th ID
                        %th #{t 'video'}
                        %th #{t 'comment'}(s)
                      %tbody
                        - @videos.each do |video|
                          %tr
                            %td #{ video.id }
                            %td= link_to video.title, post
                            %td
                              %table.table.is-striped.is-fullwidth
                                - video.comments.each do |video_comment|
                                  %tr{class: "cmtPost-#{video_comment.id}"}
                                    %td #{ video_comment.commenter }
                                    %td #{ video_comment.status }
                                    %td{width: '5px'}
                                      .action{data:{post:{comment: "#{update_comment(video_comment.id, 'published')}"}}}
                                        .btn_comment_published
                                          %i.fas.fa-lock
                                    %td{width: '5px'}
                                      %span
                                        %i.fas.fa-trash

                  .tab_wrapper
                    %table.table.is-striped.is-fullwidth
                      %thead
                        %tr
                          %th #
                          %th #{t 'date_at'}
                          %td #{t 'requested'}
                          %td Username
                          %td
                      %tbody
                        - Friend.list_friend_pending(current_user.id).each do |friend|
                          %tr{class: "social-#{friend.id}"}
                            %td #{ friend.id }
                            %td #{ l friend.created_at ,format: :long }
                            %td #{ friend.user.name }
                            %td #{ friend.user.username }
                            - if friend.status == 'pending'
                              %td
                                .action{data:{social:{id: "#{updated_friend(friend.id, 'accepted')}"}}}
                                  .btn_social
                                    %i.fas.fa-lock

                  .tab_wrapper
                    %table.table.is-striped.is-fullwidth
                      %thead
                        %tr
                          %th #
                          %th #{t 'date_at'}
                          %td #{t 'requested'}
                          %td Username
                          %td
                      %tbody
                        - Friend.list_friend(current_user.id).each do |friend|
                          %tr{class: "social-#{friend.id}"}
                            %td #{ friend.id }
                            %td #{ l friend.created_at ,format: :long }
                            %td #{ friend.user.name }
                            %td #{ friend.user.username }
                            - if friend.status == 'pending'
                              %td
                                .action{data:{social:{id: "#{block_friend(friend.id, 'blocked')}"}}}
                                  .btn_social
                                    %i.fas.fa-lock
              -# .aside_perfil
              -#   aside