config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#list_posts'

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    devise_for :users

    resources :posts do
      member do
        put 'like', to: 'posts#upvote'
        put 'unlike', to: 'posts#downvote'
      end
    end

    get '/search', to: 'posts#search'
    get '/list_posts', to: 'posts#list_posts'
    get '/list_videos', to: 'posts#list_videos'
    get 'tags/:tag', to: 'posts#index', as: :tag

    resources :comments, only: %i[ create update destroy ] do
      member do
        put 'like', to: 'comments#upvote'
        put 'unlike', to: 'comments#downvote'
      end
    end

    resources :friends, only: %i[ create update destroy ]

    resources :users, only: %i[ show ]
    get '/profile_edit', to: 'users#edit'
    patch '/profile', to: 'users#updade'

end

app/views/shared/_banner.html.haml
.container
  .wrapper_banner.pb-0
    = image_tag ('https://picsum.photos/800/600'), class: 'fig'

app/views/shared/_footer.html.haml
.footer.has-background-dark
  .container
    .footer-container
      .footer-logo
        = image_tag 'news.png', style: 'width: 60px'
        %div
          %h1.title.is-4.has-text-white news-up
      .footer-content
        w3n design &copy; #{ Date.current.year }
      .footer-social
        = link_to '#' do
          %i.fab.fa-facebook-square.fa-2x
          %div
            %small facebook
        = link_to '#' do
          %i.fab.fa-twitter-square.fa-2x
          %div
            %small twitter
        = link_to '#' do
          %i.fab.fa-instagram-square.fa-2x
          %div
            %small instagram
        = link_to '#' do
          %i.fab.fa-discord.fa-2x
          %div
            %small discord

app/views/shared/_menubar.html.haml
%nav.navbar.is-dark
  .container
    .navbar-brand
      = link_to root_path, class: 'navbar-item' do
        = image_tag 'news.png'
        %h2.ml-4 news-up
      .navbar-burger.burger{data:{target: 'menubar'}}
        %span{aria:{hidden: 'true'}}
        %span{aria:{hidden: 'true'}}
        %span{aria:{hidden: 'true'}}
    .navbar-menu#menubar
      .navbar-start
        = link_to :list_posts, class: 'navbar-item' do
          %i.far.fa-newspaper.mr-2
          #{ t 'articles' }
        = link_to :list_videos, class: 'navbar-item' do
          %i.far.fa-file-video.mr-2
          #{ t 'videos' }

      .navbar-end
        .navbar-item

          %form{action: '/search', method: :get}
            .field.has-addons.has-addons-right
              .control
                %input.input{type: 'text', name: 'q', placeholder: "#{ t 'search' }", class: 'is-small is-rounded'}
              .control
                %button.button.is-small.is-info.is-rounded{type: 'submit'}
                  %i.fas.fa-search

        -if user_signed_in? && (current_user.kind == 'admin' || current_user.kind == 'manager')
          = link_to user_path(current_user.id), class: 'navbar-item icone' do
            .social_count.px-2
              %i.fas.fa-comment
              %span
                #{ current_user.total_comments }
          = link_to user_path(current_user.id), class: 'navbar-item icone' do
            .social_count.px-2
              %i.fas.fa-user
              %span
                #{ Friend.pendings_friends(current_user.id) }
          .navbar-item.has-dropdown.is-hoverable.is-flex
            = link_to '#', class: 'navbar-link' do
              .profile
                = get_avatar(current_user)
              = current_user.username
            .navbar-dropdown.is-right
              -if current_user.kind == 'manager'
                = link_to rails_admin_path, class: 'navbar-item' do
                  %i.fas.fa-user-lock.mr-2
                  #{ t 'administration' }
              = link_to user_path(current_user.id), class: 'navbar-item' do
                %i.fas.fa-list.mr-2
                #{ t 'profile' }
              = link_to new_post_path(type_subject: :post), class: 'navbar-item' do
                %i.fas.fa-newspaper.mr-2
                #{ t 'add_article' }
              = link_to new_post_path(type_subject: :video), class: 'navbar-item' do
                %i.far.fa-file-video.mr-2
                #{ t 'add_video' }
              = link_to edit_user_registration_path, class: 'navbar-item' do
                %i.fas.fa-user.mr-2
                #{ t 'edit_register' }
              = link_to profile_edit_path, class: 'navbar-item' do
                %i.fas.fa-portrait.mr-2
                #{ t 'avatar' }
              .navbar-divider
              = link_to destroy_user_session_path, method: :delete, class: 'navbar-item', data: {confirm: "#{ t 'are_you_sure'}"} do
                %i.fas.fa-door-open.mr-2
                #{ t 'exit' }

        - elsif user_signed_in?
          .navbar-item.has-dropdown.is-hoverable.is-flex
            = link_to '#', class: 'navbar-link' do
              .profile
                = get_avatar(current_user)
              = current_user.username
            .navbar-dropdown.is-right
              = link_to edit_user_registration_path, class: 'navbar-item' do
                %i.fas.fa-user.mr-2
                #{ t 'edit_register' }
              = link_to profile_edit_path, class: 'navbar-item' do
                %i.fas.fa-user.mr-2
                #{ t 'avatar' }
              .navbar-divider
              = link_to destroy_user_session_path, method: :delete, class: 'navbar-item', data: {confirm: "#{ t 'are_you_sure'}"} do
                %i.fas.fa-door-open.mr-2
                #{ t 'exit' }

        - else
          = link_to new_user_session_path, class: 'navbar-item is-small' do
            %i.fas.fa-sign-in-alt.mr-2
            #{ t 'login' }
          .navbar-item
            = link_to new_user_registration_path, class: 'button is-info is-small is-rounded' do
              %i.fas.fa-pencil-alt.mr-2
              #{ t 'signup' }

        .navbar-item
          - if user_signed_in?
            = link_to '#', id: 'modal_language', data: {modal_id: 'user-actions'} do
              = language_user(current_user.language)

app/views/shared/_tags.html.haml
.aside_container
  .titles
    %i.fas.fa-tags
    tags
  .post_tags
    .tag_cloud
      - tag_cloud Post.tag_counts, %i[ s m l ] do |tag, css_class|
        %span
          = link_to tag.name, tag_path(tag.name), class: css_class

app/views/shared/_user_action_modal.html.haml
#user-actions.modals
  