config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#list_posts'

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    devise_for :users

    resources :posts do
      member do
        put 'like', to: 'posts#upvote'
        put 'unlike', to: 'posts#downvote'
      end
    end

    get '/search', to: 'posts#search'
    get '/list_posts', to: 'posts#list_posts'
    get '/list_videos', to: 'posts#list_videos'
    get 'tags/:tag', to: 'posts#index', as: :tag

    resources :comments, only: %i[ create update destroy ] do
      member do
        put 'like', to: 'comments#upvote'
        put 'unlike', to: 'comments#downvote'
      end
    end

    resources :friends, only: %i[ create update destroy ]

    resources :users, only: %i[ show ]
    get '/profile_edit', to: 'users#edit'
    patch '/profile', to: 'users#updade'

end

app/models/post.rb
class Post < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  acts_as_votable

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :upload
  has_one_attached :streaming
  has_rich_text :body
  acts_as_taggable_on :tags

  enum contrast: [ :simple, :enphasis ]
  enum type_subject: [:post, :video]

  scope :listposts, -> { where(type_subject: :post) }
  scope :listvideos, -> { where(type_subject: :video) }
  # scope :list_comments_posts, -> { joins(:comments).where(type_subject: :post, comments: {status: :pending}).distinct }
  # scope :list_comments_videos, -> { joins(:comments).where(type_subject: :video, comments: {status: :pending}).distinct }
  scope :comments_post_not_published, -> { joins(:comments).where(type_subject: :post).where.not(comments: {status: :published}).distinct }
  scope :comments_video_not_published, -> { joins(:comments).where(type_subject: :video).where.not(comments: {status: :published}).distinct }

  validates :upload, presence: true

  def total_comments
    self.comments.where(status: :pending).count
  end

  def self.search(search)
    where("title LIKE ?", "%" + search + "%")
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: %i[ show edit update destroy upvote downvote]

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).order(created_at: :desc).page(params[:page]).per(12)
    else
      @posts = Post.page(params[:page]).per(24)
    end
  end

  def list_posts
    @posts = Post.listposts.order(created_at: :desc).page(params[:page]).per(12)
  end

  def list_videos
    @posts = Post.listvideos.order(created_at: :desc).page(params[:page]).per(12)
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_param.merge(user: current_user))
    if current_user.kind == 'admin' || current_user.kind == 'manager'
      if @post.save
        redirect_to @post, notice: 'Post created successfully!!!'
      else
        flash.now[:alert] = @post.errors.full_messages.to_sentence
        render :new
      end
    else
      render :index
    end
  end

  def updade
    if @post.update(post_params)
      redirect_to @post, notice: 'Post updated successfully!!!'
    else
      flash.now[:alert] = @post.errors.full_messages.to_setence
    end
  end

  def upvote
    @post.upvote_from current_user
    redirect_to @post
  end

  def downvote
    @post.downvote_from current_user
    redirect_to @post
  end

  def search
    # TODO: Refaturar a pesquisa em categoria
    if params[:q] != '' || params[:q] != nil

      @posts = Post.search(params[:q]).page(params[:page]).per(12)
      render :list_posts

    else
      render :list_posts
    end

  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_param
    params.require(:post).permit(:title, :body, :streaming, :upload, :type_subject, :tag_list)
  end

end

app/views/posts/_form.html.haml
%h2.has-text-centered.mb-5.mt-4
  - if params[:action] == 'edit'
    - if post.type_subject == 'post'
      #{ t 'edit_post'}
    - else
      #{ t 'edit_video'}
  - else
    #{ title }

=form_with(model: post, local: true) do |form|
  = form.hidden_field :type_subject, value: params[:type_subject]
  .field
    = form.label :title, class: 'label'
    .control
      = form.text_field :title, class: 'input'
  .field
    = form.label :tag_list, "Tags (separe as tags com virgulas)", class: 'label'
    .control
      = form.text_field :tag_list, class: 'input'
  .field
    = form.label :body, class: 'label'
    .control
      = form.rich_text_area :body, style: 'min-height: 600px; height: auto'
  - if params[:type_subject] == 'post'
    .columns
      - if params[:action] == 'edit' && post.upload.attached?
        .column.is-2
          .image_edit.has-text-right
            %span
              = image_tag post.upload
      .column
        .field
          = form.label "#{ t 'image' }", class: 'label'
          .control
            = form.file_field :upload, require: true
  - else
    .columns
      - if params[:action] == 'edit' && post.upload.attached?
        .column.is-2
          .image_edit.has-text-right
            %span
              = image_tag post.upload
      .column
        .field
          = form.label "#{'image'}", class: 'label'
          .control
            = form.file_field :upload
      .column
        - if post.type_subject != 'post'
          .field
            = form.label "#{t 'video'}", class: 'label'
            .control
              = form.file_field :streaming, require: true

  .field.has-text-right.mb-5
    = form.submit "#{ t 'confirm' }", class: 'button is-info'

app/views/posts/_posts.html.haml
.blog_container
  = link_to post_path(post) do
    .blog_header
      = get_image(post)
  .blog_main
    .blog_main_header
      .main_header_perfil
      .main_header_comments
        .icones.mr-2
          .tags.has-addons
            %span.tag
              #{ post.get_upvotes.size } &nbsp;
              %span
                %i.fas.fa-thumbs-up
            %span.tag
              #{ post.get_downvotes.size } &nbsp;
              %span
                %i.fas.fa-thumbs-down
            %span.tag
              #{ post.comments.count } &nbsp;
              %span
                %i.fas.fa-comment-alt
    .blog_main_content
      %h3.titles
        #{ post.title }
      %p
        #{ truncate(strip_tags(post.body.to_s), length: 120) }
    .blog_main_footer
      .footer_tag
        - if post.tag_list.any?
          .tag_detail
            -# %strong Tags:
          #{ raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(' ') }
      .footer_date.has-text-right
        %span
          #{ t 'by' } #{ post.user.name }
        %span
          #{ l post.created_at, format: :long }

app/views/posts/_show_post.html.haml
%main
  = render 'shared/banner'
  .container
    .wrapper_content
      .wrapper_grids
        .show_content
          .header_content
            %span
              %h1 #{ @post.title }
              .show_dates.mb-5
              #{ l @post.created_at, format: :long }
            %span
              -if user_signed_in? && current_user == @post.user
                = link_to edit_post_path(@post), class: 'tag is-info' do
                  %i.fas.fa-edit.mr-2
                  #{ t 'edit'}
                = link_to post_path(@post), method: :delete, class: 'tag is-danger ml-2', data: {confirm: "#{t 'are_you_sure?'}"} do
                  %i.fas.fa-trash.mr-2
                  #{ t 'delete'}

          .show_votable
            %div
              = render 'users/avatar', profile: @post.user
              - if @post.upload.attached?
                .show_image
                  #{ image_tag @post.upload, class: 'img_show' }
            %div
              .icones.mt-4
                .tags.has-addons
                  = link_to like_post_path(@post), method: :put, class: 'tag like' do
                    = @post.get_upvotes.size
                    %span.ml-2
                      %i.fas.fa-thumbs-up
                  = link_to unlike_post_path(@post), method: :put, class: 'tag like' do
                    = @post.get_downvotes.size
                    %span.ml-2
                      %i.fas.fa-thumbs-down
                  %span.tag
                    %b.mr-2 #{ @post.comments.published.count }
                    #{ t 'comment' }(s) &nbsp;
                    %span
                      %i.fas.fa-comment-alt

          .show_description
            %p #{ @post.body }

          .post_comments
            = render 'comments/form', origem: @post

          - if @post.comments.any?
            = render 'comments/comments', commenter: @post.comments

        .grid_aside
          = render 'users/perfil_follow', profile: @post.user
          = render 'shared/tags'

app/views/posts/_show_video.html.haml
%link{href: "https://vjs.zencdn.net/7.10.2/video-js.css", rel: "stylesheet"}
%main
  = render 'shared/banner'
  .container
    .wrapper_content
      .wrapper_grids
        .show_content
          .header_content
            %span
              %h1 #{ @post.title }
              .show_dates.mb-5
              #{ l @post.created_at, format: :long }
            %span
              -if user_signed_in? && current_user == @post.user
                = link_to edit_post_path(@post), class: 'tag is-info' do
                  %i.fas.fa-edit.mr-2
                  #{ t 'edit'}
                = link_to post_path(@post), method: :delete, class: 'tag is-danger ml-2', data: {confirm: "#{t 'are_you_sure?'}"} do
                  %i.fas.fa-trash.mr-2
                  #{ t 'delete'}
          .show_votable
            %div
              = render 'users/avatar', profile: @post.user
              - if @post.upload.attached?
                .streaming_container.has-text-centered.mt-3
                  %span
                    %video{id: "my-video", class: "video-js", controls: '', preload: "auto", width: "640", height: "", poster: "#{url_for(@post.upload)}", data:{setup:"{}"}}
                      %source{src: "#{url_for(@post.streaming)}", type: "video/mp4"}
            %div
              .icones.mt-4
                .tags.has-addons
                  = link_to like_post_path(@post), method: :put, class: 'tag like' do
                    = @post.get_upvotes.size
                    %span.ml-2
                      %i.fas.fa-thumbs-up
                  = link_to unlike_post_path(@post), method: :put, class: 'tag like' do
                    = @post.get_downvotes.size
                    %span.ml-2
                      %i.fas.fa-thumbs-down
                  %span.tag
                    %b.mr-2 #{ @post.comments.count }
                    #{ t 'comment' }(s) &nbsp;
                    %span
                      %i.fas.fa-comment-alt

          .show_description
            %p #{ @post.body }

          .post_comments
            = render 'comments/form', origem: @post

          - if @post.comments.any?
            = render 'comments/comments', commenter: @post.comments

        .grid_aside
          = render 'users/perfil_follow', profile: @post.user
          = render 'shared/tags'

%script{src: "https://vjs.zencdn.net/7.10.2/video.min.js"}

app/views/posts/_videos.html.haml
.video_container
  = link_to post_path(post) do
    .video_thumbnail
      = get_image(post, 'adjust_image')
  .video_description
    .video_avatar
      = get_avatar(post.user)
    .video_detail.ml-3
      %div{style: 'flex: 1'}
        .video_title
          = truncate post.title, length: 50
        .video_author
          = post.user.name
        .video_published
          = time_ago_in_words post.created_at
      .video_social
        .icones.mr-2
          .tags.has-addons
            %span.tag
              #{ post.get_upvotes.size } &nbsp;
              %span
                %i.fas.fa-thumbs-up
            %span.tag
              #{ post.get_downvotes.size } &nbsp;
              %span
                %i.fas.fa-thumbs-down
            %span.tag
              #{ post.comments.count } &nbsp;
              %span
                %i.fas.fa-comment-alt

app/views/posts/edit.html.haml
%main.mb-5
  .container.mt-5
    .wrapper_form
      .columns.is-centered
        .column.is-8
          - if params[:type_subject] == 'post'
            = render 'form', post: @post, title: "#{ t 'add_article' }"
          - else
            = render 'form', post: @post, title: "#{ t 'add_video' }"

app/views/posts/index.html.haml
%main
  = render 'shared/banner'
  .container
    .wrapper_content
      .wrapper_grids
        .grid_content
          - @posts.each do |post|
            .blog_container
              = link_to post_path(post) do
                .blog_header
                  = get_image(post)
              .blog_main
                .blog_main_header
                  .main_header_perfil
                  .main_header_comments
                    .icones.mr-2
                      .tags.has-addons
                        %span.tag
                          780 &nbsp;
                          %span
                            %i.fas.fa-thumbs-up
                        %span.tag
                          21 &nbsp;
                          %span
                            %i.fas.fa-thumbs-down
                        -# %span.tag
                          Share &nbsp;
                          %span
                            %i.fas.fa-retweet
                        %span.tag
                          544 Comments &nbsp;
                          %span
                            %i.fas.fa-comment-alt
                .blog_main_content
                  %h3.titles
                    #{ post.title }
                  %p
                    #{ truncate(strip_tags(post.body.to_s), length: 120) }
                .blog_main_footer
                  .footer_tag
                    - if post.tag_list.any?
                      .tag_detail
                        -# %strong Tags:
                      #{ raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(' ') }
                  .footer_date.has-text-right
                    %span
                      #{ t 'by' } #{ post.user.name }
                    %span
                      #{ l post.created_at, format: :long }
        .grid_aside
          = render 'shared/tags'

app/views/posts/list_posts.html.haml
%main
  = render 'shared/banner'
  .container
    .wrapper_content
      .wrapper_grids
        .grid_content

          - @posts.each do |post|
            - cache post do
              =render 'posts', post: post

        .grid_aside
          = render 'shared/tags'

    .pagination
      = paginate @posts
%br

app/views/posts/list_videos.html.haml
%main
  = render 'shared/banner'
  .container
    .wrapper_content
      .wrapper_grids
        .grid_content.has-background-white{style: 'border-radius: 5px; padding: 1rem'}
          - @posts.each do |post|
            - cache post do
              = render 'videos', post: post

        .grid_aside
          = render 'shared/tags'

app/views/posts/new.html.haml
%main.mb-5
  .container.mt-5
    .wrapper_form
      .columns.is-centered
        .column.is-8
          - if params[:type_subject] == 'post'
            = render 'form', post: @post, title: "#{ t 'add_article' }"
          - else
            = render 'form', post: @post, title: "#{ t 'add_video' }"

app/views/posts/show.html.haml
%main
  = render 'shared/banner'
  .container
    .wrapper_content
      .wrapper_grids
        .show_content
          %h1 #{ @post.title }
          .show_dates.mb-5
            #{ l @post.created_at, format: :long }
          .show_votable
            %div
              = render 'users/avatar', profile: @post.user
              - if @post.upload.attached?
                .show_image
                  #{ image_tag @post.upload, class: 'img_show' }
            %div
              .icones.mt-4
                .tags.has-addons
                  = link_to like_post_path(@post), method: :put, class: 'tag like' do
                    = @post.get_upvotes.size
                    %span.ml-2
                      %i.fas.fa-thumbs-up
                  = link_to unlike_post_path(@post), method: :put, class: 'tag like' do
                    = @post.get_downvotes.size
                    %span.ml-2
                      %i.fas.fa-thumbs-down
                  %span.tag
                    %b.mr-2 #{ @post.comments.count }
                    #{ t 'comment' }(s) &nbsp;
                    %span
                      %i.fas.fa-comment-alt

          .show_description
            %p #{ @post.body }

          .post_comments
            = render 'comments/form', origem: @post

          - if @post.comments.any?
            = render 'comments/comments', commenter: @post.comments

        .grid_aside
          = render 'users/perfil_follow', profile: @post.user
          = render 'shared/tags'